# Generated by Django 5.1.7 on 2025-03-08 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adoptee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63, null=True)),
                ('breed', models.CharField(max_length=31)),
                ('age', models.IntegerField()),
                ('photo', models.ImageField(max_length=255, upload_to=None)),
                ('species', models.CharField(max_length=63)),
            ],
        ),
    ]
