# Generated by Django 5.1.7 on 2025-03-08 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptee',
            name='name',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='adoptee',
            name='photo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=None),
        ),
    ]
